AWS_BUCKET: prod-albums  
AWS_ACCESS_KEY_ID: AKIAIC7BPWT7TT54CM7A   
AWS_SECRET_ACCESS_KEY: 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
ROVI_API_KEY: "nwd2tkdxysudvbyw4br6w77p"
ROVI_SECRET_KEY: "Ca8ZR2uuAA"